#!/usr/bin/env python3
"""Push a notification when a to-do with a time on it comes due.

Plain English: a to-do can carry a `due_by` date and a `due_time` ("07:00").
Until now that time was decoration — nothing anywhere watched the clock. This
script is the thing that watches. Run by cron once a minute, it looks for
to-dos due TODAY whose time has arrived, and asks the server to push one
notification per to-do to her phone.

    * * * * * /usr/bin/python3 /opt/exocortex/skeleton/scripts/todo_push_dispatcher.py

(The owner wires up the actual crontab — this script just needs to be runnable
by system python3 with no venv/third-party deps, same as prompt_dispatcher.py,
whose shape this follows throughout.)

How it decides, in order:
  - not done, not snoozed, has an id, `due_by` is today, has a `due_time`;
  - that time has passed;
  - it hasn't already fired today (see the state file below);
  - it isn't more than GRACE_MINUTES late. A 7 AM reminder arriving at 4 PM
    isn't a reminder, it's noise — the machine slept, the moment passed, and
    pretending otherwise trains her to ignore the buzz. Those are recorded as
    "missed" so they never fire, rather than left pending to ambush her later.

Firing state lives in its own collection, todo_push_state.json, keyed by
to-do id — deliberately NOT a field on the to-do itself. Stamping todos.json
would put scheduler bookkeeping inside her data, and worse, every write there
goes through routes/todos.py's journal re-render machinery, which exists for
completion facts and has no business being woken by a notification.
Entries for other days are pruned on every run, so the file stays small and
an item that comes due again tomorrow fires again.

Delivery goes through POST /api/push/notify (routes/push.py) with the
`reminder` event — the same localhost, shared-secret door the Claude Code
hooks use. No new authentication, no new route. A reminder is NOT
presence-suppressed: it arrives whether or not the app is open.

Times are read as server-local. That's correct as long as the server's clock
is set to the timezone she lives in; there is no per-user timezone anywhere
in this app, and inventing one here would be the only place it existed.
"""
import json
import os
import sys
import urllib.request
from datetime import datetime
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent

# Same store-if-importable-else-reimplement dance as prompt_dispatcher.py:
# prefer the repo's atomic JSON layer, but stay runnable when sys.path can't
# find it.
try:
    sys.path.insert(0, str(REPO_ROOT))
    import store  # noqa: E402  (repo's atomic JSON layer; stdlib-only itself)
except Exception:
    store = None

if store is not None:
    DATA_DIR = store.DATA_DIR
else:
    DATA_DIR = Path(os.environ.get("EXOCORTEX_DATA_DIR", str(REPO_ROOT / "data")))

NOTIFY_URL = os.environ.get("EXOCORTEX_PUSH_NOTIFY_URL", "http://127.0.0.1:5000/api/push/notify")
STATE_FILE = "todo_push_state.json"
SECRET_FILE = "push_hook_secret"
DONE_KEY = "done"
# Where a reminder tap lands. The to-dos page, not the chat the agent
# notifications open.
TAP_URL = "/todos"
# How late a reminder may be and still be worth sending.
GRACE_MINUTES = 120
_TEXT_TRUNCATE = 70


def read_json(name, default):
    if store is not None:
        return store.read(name, default)
    path = DATA_DIR / name
    if not path.exists():
        return default
    return json.loads(path.read_text())


def write_json(name, data):
    if store is not None:
        store.write(name, data)
        return
    path = DATA_DIR / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False))


def _data_dir():
    """Resolved fresh on every call rather than read off the module-level
    DATA_DIR — same reasoning as routes/push.py's _vapid_pem_path: store's
    root is what tests monkeypatch, and a value captured at import time
    would point at the real vault from inside a test."""
    return store.DATA_DIR if store is not None else DATA_DIR


def hook_secret():
    """The shared secret /api/push/notify checks. Generated by the server on
    first need (routes/push.py::_hook_secret) — never minted here, since a
    cron script writing the server's credential is how you end up with two
    different secrets and a door that stops opening."""
    try:
        return (_data_dir() / SECRET_FILE).read_text().strip()
    except OSError:
        return ""


def due_items(todos, now):
    """Every to-do that wants a push at `now`, as (item, due_datetime) pairs.

    Walks every ladder bucket except Done. Items are skipped for the ordinary
    reasons they'd be invisible in the UI too — done, snoozed — so the phone
    never contradicts the screen."""
    today = now.strftime("%Y-%m-%d")
    out = []
    for key, section in (todos or {}).items():
        if key == DONE_KEY or not isinstance(section, dict):
            continue
        for item in section.get("items", []):
            if not isinstance(item, dict) or item.get("done"):
                continue
            if not item.get("id"):
                continue  # no stable id = nothing to dedupe against
            if item.get("due_by") != today:
                continue
            due_time = (item.get("due_time") or "").strip()
            if not due_time:
                continue
            snoozed = item.get("snoozed_until")
            if snoozed and snoozed > today:
                continue
            try:
                due_at = datetime.strptime(f"{today} {due_time}", "%Y-%m-%d %H:%M")
            except ValueError:
                continue  # unparsable time: not due, and not our job to fix
            if due_at <= now:
                out.append((item, due_at))
    return out


def send_push(secret, item, due_at):
    """POST one reminder through the hook door. Returns True when the server
    says at least one device actually got it."""
    text = (item.get("text") or "").strip()
    if len(text) > _TEXT_TRUNCATE:
        text = text[:_TEXT_TRUNCATE - 1] + "…"
    body = {
        "secret": secret,
        "event": "reminder",
        "title": f"⏰ {text}" if text else "⏰ Reminder",
        "body": due_at.strftime("%-I:%M %p").lower(),
        "url": TAP_URL,
    }
    req = urllib.request.Request(
        NOTIFY_URL,
        data=json.dumps(body).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=10) as resp:
        payload = json.loads(resp.read() or b"{}")
    return bool(payload.get("sent"))


def process_due(now=None):
    """One pass: fire everything due, record what happened, prune yesterday.

    Each to-do is handled in its own try/except — one unreachable server or
    malformed item never stops the rest of the batch. Returns the state dict
    that was written."""
    now = now or datetime.now()
    today = now.strftime("%Y-%m-%d")

    state = read_json(STATE_FILE, {"fired": {}})
    fired = state.setdefault("fired", {})
    # Yesterday's records have done their job; dropping them is also what lets
    # a repeating errand fire again on its next due day.
    for todo_id in [k for k, v in fired.items()
                    if not isinstance(v, dict) or v.get("on") != today]:
        del fired[todo_id]

    todos = read_json("todos", {})
    candidates = due_items(todos, now)
    if not candidates:
        write_json(STATE_FILE, state)
        return state

    secret = hook_secret()
    if not secret:
        # Loud, not silent: a dispatcher that quietly does nothing forever is
        # indistinguishable from one that's working until she misses something.
        print("todo_push_dispatcher: no push_hook_secret in the data dir — "
              "cannot authenticate to /api/push/notify", file=sys.stderr)
        return state

    for item, due_at in candidates:
        todo_id = item["id"]
        if todo_id in fired:
            continue
        late_minutes = (now - due_at).total_seconds() / 60
        if late_minutes > GRACE_MINUTES:
            fired[todo_id] = {"on": today, "at": due_at.strftime("%H:%M"),
                              "status": "missed"}
            continue
        try:
            delivered = send_push(secret, item, due_at)
        except Exception as e:
            # Left OUT of `fired`, so the next minute's run tries again —
            # a transient blip shouldn't cost her the reminder.
            print(f"todo_push_dispatcher: {todo_id} failed: {e}", file=sys.stderr)
            continue
        fired[todo_id] = {"on": today, "at": due_at.strftime("%H:%M"),
                          "status": "sent" if delivered else "undelivered"}

    write_json(STATE_FILE, state)
    return state


def main():
    process_due()


if __name__ == "__main__":
    main()
